#!/usr/bin/env bash
#
# import_dev.sh — Import TSV exports into local dev database and mask PII
#
# Usage:
#   ./import_dev.sh <client> [mysql_user] [mysql_pass] [mysql_host] [mysql_port] [mongo_host] [mongo_port]
#
# Defaults:
#   mysql_user=root, mysql_pass=root, mysql_host=127.0.0.1, mysql_port=3306
#   mongo_host=127.0.0.1, mongo_port=27017
#
# Prerequisites:
#   - Local MySQL/MariaDB running (via Docker or native)
#   - TSV files in data/<client>/ (generated by extract_prod.sh)
#   - Docker container pyr-<client> running (for schema load)
#
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <client> [mysql_user] [mysql_pass] [mysql_host] [mysql_port] [mongo_host] [mongo_port]"
  exit 1
fi

CLIENT="$1"
MYSQL_USER="${2:-root}"
MYSQL_PASS="${3:-root}"
MYSQL_HOST="${4:-127.0.0.1}"
MYSQL_PORT="${5:-3306}"
MONGO_HOST="${6:-127.0.0.1}"
MONGO_PORT="${7:-27017}"

DB_NAME="pyr_${CLIENT}_dev"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DATA_DIR="${SCRIPT_DIR}/data/${CLIENT}"
MASK_SQL="${SCRIPT_DIR}/mask_pii.sql"

MYSQL_CMD="mysql --default-character-set=utf8mb4 -h ${MYSQL_HOST} -P ${MYSQL_PORT} -u ${MYSQL_USER} -p${MYSQL_PASS}"

# Verify data directory exists
if [[ ! -d "$DATA_DIR" ]]; then
  echo "ERROR: Data directory not found: ${DATA_DIR}"
  echo "Run extract_prod.sh first to generate TSV files."
  exit 1
fi

TSV_COUNT=$(find "$DATA_DIR" -name "*.tsv" | wc -l)
if [[ "$TSV_COUNT" -eq 0 ]]; then
  echo "ERROR: No TSV files found in ${DATA_DIR}"
  exit 1
fi

echo "================================================"
echo "Importing dev dataset for: ${CLIENT}"
echo "Database: ${DB_NAME} @ ${MYSQL_HOST}:${MYSQL_PORT}"
echo "Source:   ${DATA_DIR}/ (${TSV_COUNT} TSV files)"
echo "================================================"
echo ""

# --- Step 1: Drop & recreate database ---
echo "[Step 1] Recreating database ${DB_NAME}..."
$MYSQL_CMD -e "DROP DATABASE IF EXISTS ${DB_NAME}; CREATE DATABASE ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "  Done."
echo ""

# --- Step 2: Load schema via Docker ---
echo "[Step 2] Loading schema via Docker (pyr-${CLIENT})..."
CONTAINER_NAME="pyr-${CLIENT}"
if docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
  docker exec "$CONTAINER_NAME" bundle exec rake db:schema:load RAILS_ENV=development 2>&1 | tail -5
  echo "  Schema loaded."
else
  echo "  WARNING: Container ${CONTAINER_NAME} not running."
  echo "  Attempting schema load via docker-compose..."
  if [[ -f "${SCRIPT_DIR}/../docker-compose.yml" ]]; then
    (cd "${SCRIPT_DIR}/.." && docker compose run --rm "$CLIENT" bundle exec rake db:schema:load RAILS_ENV=development 2>&1 | tail -5)
    echo "  Schema loaded via docker-compose."
  else
    echo "  ERROR: Cannot load schema. Start the container first:"
    echo "    ~/pyr-docker/pyr.sh up ${CLIENT}"
    exit 1
  fi
fi
echo ""

# --- Step 3: Import TSV files ---
echo "[Step 3] Importing TSV data..."
$MYSQL_CMD "$DB_NAME" -e "SET FOREIGN_KEY_CHECKS = 0;"

IMPORT_ERRORS=0
for tsv_file in "${DATA_DIR}"/*.tsv; do
  [ -f "$tsv_file" ] || continue
  table_name="$(basename "$tsv_file" .tsv)"

  # Check if table exists in schema
  TABLE_EXISTS=$($MYSQL_CMD "$DB_NAME" -N -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='${DB_NAME}' AND TABLE_NAME='${table_name}'")
  if [[ "$TABLE_EXISTS" -eq 0 ]]; then
    echo "  SKIP: ${table_name} (table not in schema)"
    continue
  fi

  # Get column count from .cols file if available
  COLS_FILE="${DATA_DIR}/${table_name}.cols"

  echo -n "  Loading ${table_name}..."
  ROW_COUNT=$(wc -l < "$tsv_file")

  # Truncate first to avoid duplicates
  $MYSQL_CMD "$DB_NAME" -e "TRUNCATE TABLE ${table_name};" 2>/dev/null || true

  # Import using LOAD DATA LOCAL INFILE
  $MYSQL_CMD --local-infile=1 "$DB_NAME" -e "
    LOAD DATA LOCAL INFILE '${tsv_file}'
    INTO TABLE ${table_name}
    CHARACTER SET utf8mb4
    FIELDS TERMINATED BY '\t'
    LINES TERMINATED BY '\n'
    ;
  " 2>/dev/null
  RESULT=$?

  if [[ $RESULT -eq 0 ]]; then
    echo " ${ROW_COUNT} rows"
  else
    echo " FAILED"
    IMPORT_ERRORS=$((IMPORT_ERRORS + 1))
  fi
done

$MYSQL_CMD "$DB_NAME" -e "SET FOREIGN_KEY_CHECKS = 1;"
echo ""

if [[ $IMPORT_ERRORS -gt 0 ]]; then
  echo "  WARNING: ${IMPORT_ERRORS} table(s) failed to import."
fi

# --- Step 4: Mask PII ---
echo "[Step 4] Masking PII..."
if [[ -f "$MASK_SQL" ]]; then
  $MYSQL_CMD "$DB_NAME" < "$MASK_SQL" 2>&1 | grep -v "^$" || true
  echo "  PII masked."
else
  echo "  WARNING: mask_pii.sql not found at ${MASK_SQL}, skipping PII masking!"
fi
echo ""

# --- Step 5: Import MongoDB ---
JSON_COUNT=$(find "$DATA_DIR" -name "*.json" 2>/dev/null | wc -l)
if [[ "$JSON_COUNT" -gt 0 ]]; then
  echo "[Step 5] Importing MongoDB collections..."
  MONGO_DB="pyr_${CLIENT}_development"

  for json_file in "${DATA_DIR}"/*.json; do
    [ -f "$json_file" ] || continue
    collection_name="$(basename "$json_file" .json)"
    echo -n "  Loading ${collection_name}..."

    # Drop existing collection and import
    mongosh --host "$MONGO_HOST" --port "$MONGO_PORT" "$MONGO_DB" \
      --eval "db.${collection_name}.drop()" --quiet 2>/dev/null || true

    mongoimport --host "$MONGO_HOST" --port "$MONGO_PORT" \
      --db "$MONGO_DB" --collection "$collection_name" \
      --file "$json_file" --quiet 2>/dev/null
    RESULT=$?

    if [[ $RESULT -eq 0 ]]; then
      ROW_COUNT=$(wc -l < "$json_file")
      echo " ${ROW_COUNT} documents"
    else
      echo " FAILED"
    fi
  done
  echo ""
else
  echo "[Step 5] No MongoDB JSON files found, skipping."
  echo ""
fi

# --- Summary ---
echo "================================================"
echo "Import complete for: ${CLIENT}"
echo "Database: ${DB_NAME}"
echo ""
echo "Verify with:"
echo "  docker exec -it pyr-${CLIENT} rails console"
echo "  > PyrTree::User.count"
echo "  > PyrTree::Period.count"
echo "  > PyrTree::User.first.email  # should be dev+N@example.com"
echo "  > PyrTree::Sponsor.roots.count"
echo "================================================"
